// Provider-agnostic AI entry point. Every controller should import from here (never
// reach into utils/ai/providers/* directly) so switching providers is a single env var.
//
// AI_PROVIDER=claude (default) - Anthropic Claude, requires ANTHROPIC_API_KEY
// AI_PROVIDER=ollama           - local model via Ollama, no API key/rate limits
import { withCache } from './cache.js';

const providerName = (process.env.AI_PROVIDER || 'claude').toLowerCase();

const loadProvider = () => {
    if (providerName === 'ollama') return import('./providers/ollamaProvider.js');
    return import('./providers/claudeProvider.js');
};

// Resolved once at process start - restart the server after changing AI_PROVIDER.
const provider = await loadProvider();

// Cache key includes the provider name so switching providers can't serve a cached
// response generated by a different model.
const cached = (name, args, fn) => withCache(`${providerName}:${name}`, args, fn);

export const generateFlashcards = (...args) => cached('generateFlashcards', args, () => provider.generateFlashcards(...args));
export const generateQuiz = (...args) => cached('generateQuiz', args, () => provider.generateQuiz(...args));
export const generateSummary = (...args) => cached('generateSummary', args, () => provider.generateSummary(...args));
export const chatWithContext = (...args) => cached('chatWithContext', args, () => provider.chatWithContext(...args));
export const generateTopics = (...args) => cached('generateTopics', args, () => provider.generateTopics(...args));
export const classifyTopicKnowledge = (...args) => cached('classifyTopicKnowledge', args, () => provider.classifyTopicKnowledge(...args));
export const identifyWeakConcepts = (...args) => cached('identifyWeakConcepts', args, () => provider.identifyWeakConcepts(...args));
export const generateRelatedResources = (...args) => cached('generateRelatedResources', args, () => provider.generateRelatedResources(...args));
export const explainConcept = (...args) => cached('explainConcept', args, () => provider.explainConcept(...args));
